name: CI

on:
  push:
  pull_request:

jobs:
  client:
    name: Client - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

  server:
    name: Server - sanity check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Node syntax check
        run: node -c src/index.js

      - name: Prisma validate
        run: npx prisma validate
        env:
          DATABASE_URL: "postgresql://user:password@localhost:5432/kumpulbareng_ci"

  k8s:
    name: K8s Manifest Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Validasi struktur YAML
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint k8s YAML
        run: |
          yamllint -d '{extends: default, rules: {line-length: disable}}' k8s/*.yaml


      # Validasi schema Kubernetes TANPA cluster
      - name: Install kubeconform
        run: |
          curl -L -o /tmp/kubeconform.tar.gz \
            https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz
          tar -xzf /tmp/kubeconform.tar.gz -C /tmp
          sudo mv /tmp/kubeconform /usr/local/bin/kubeconform

      - name: Validate Kubernetes manifests (offline)
        run: |
          kubeconform \
            -summary \
            -ignore-missing-schemas \
            -kubernetes-version 1.30.0 \
            k8s/*.yaml

  terraform:
    name: Terraform - fmt check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive
